version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:coffeedb
      - SPRING_DATASOURCE_DRIVER_CLASS=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
    depends_on:
      - db


  db:
    image: oscarfonts/h2
    container_name: h2_database
    ports:
      - "9092:9092"
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -ifNotExists
    volumes:
      - h2data:/opt/h2-data

volumes:
  h2data:
    driver: local
